first commit diploma
MashaChornaya/Prestashop pull request #2
Opened 2022-08-30 18:59 UTC by MashaChornaya

2022-09-01 19:27 UTC, voropa requested changes

2022-09-01 19:27 UTC, voropa commented on src/test/java/Pages/AddressesPage.java
> +    private final static By state= By.xpath("//select[@id='id_state']/option[3]");
Почему тут захардкодан индекс 3?

2022-09-01 19:27 UTC, voropa commented on src/test/java/Pages/AddressesPage.java
> +        log.info("Set '{Masha}' from Cart Test");
Вы неправильно передаете входные параметры в логирование, я вам уже писал такой комментарий с пояснениями в SauceDemo репозитории. Если не разобрались, то напомните мне на занятии, расскажу еще раз

2022-09-01 19:27 UTC, voropa commented on src/test/java/Pages/AuthenticationPage.java
> +        log.info(String.format("Set email = %s", email));
Вот, тут уже правильно логировнаие реализовано

2022-09-01 19:27 UTC, voropa commented on src/test/java/Pages/DressesPage.java
> +public class DressesPage extends BasePage {
Не думаю, что страница Dresses сильно отличается от страницы T-Shirts, там структура одна  и та же, и по  сути, это  страница со списком товаров. Так что я бы не привязывался к dresses, а назвал бы страницу обобщенно, типа CatalogPage или ProductsPage

2022-09-01 19:27 UTC, voropa commented on src/test/java/Pages/DressesPage.java
> +    private final static By casualDresses = By.xpath("//div[@id='categories_block_left']/descendant::a[@href='http://prestashop.qatestlab.com.ua/ru/9-casual-dresses']");
Не очень хорошие локаторы, их нельзя упростить?

2022-09-01 19:27 UTC, voropa commented on src/test/java/Pages/DressesPage.java
> +private final static By item1=By.xpath("//a[@title='Printed Dress' and @class='product-name']");
Плохое название переменной item1

2022-09-01 19:27 UTC, voropa commented on src/test/java/Pages/HomePage.java
> +    private final By dressesSection = By.xpath("//ul[@class='sf-menu clearfix menu-content sf-js-enabled sf-arrows']/descendant::a[@title='Dresses'][2]");
Плохие локаторы

2022-09-01 19:27 UTC, voropa commented on src/test/java/Pages/ItemDetailPage.java
> +    private final static By clickContinueShoppingButton = By.xpath("//span[@title='Продолжить покупки']");
А что, если выбрать другой язык на сайте? Ваш локатор не будет работать...

2022-09-01 19:27 UTC, voropa commented on src/test/java/Tests/AuthenticationTest.java
> +        //createAnAccountPage.clickToDayOfBirthSelect();
?

2022-09-04 17:31 UTC, MashaChornaya commented on src/test/java/Pages/DressesPage.java
> +    private final static By casualDresses = By.xpath("//div[@id='categories_block_left']/descendant::a[@href='http://prestashop.qatestlab.com.ua/ru/9-casual-dresses']");
Пробовала, из-за кучи повторяющихся строчек на одной странице, сложно найти уникальный локатор. Всё что смогла найти - это такой корявенький

2022-09-12 07:40 UTC, voropa requested changes

2022-09-12 07:40 UTC, voropa commented on src/test/java/Pages/CartPage.java
> +    private final static By itemName=By.xpath("//p[@class='product-name']/a[@href and text()='Blouse']");
А что если в корзину будет добавлен другой товар, не 'Blouse'?

2022-09-12 07:40 UTC, voropa commented on src/test/java/Tests/BaseTest.java
> +    //final static String EMAIL="mashabigdreams@gmail.com";
?

2022-09-12 07:40 UTC, voropa commented on src/test/java/Tests/CartTest.java
> +       //productsPage.openItemByName(PRODUCT_NAME);
?

2022-09-12 07:40 UTC, voropa commented on src/test/java/Tests/CartTest.java
> +        //productsPage.openItemByName(PRODUCT_NAME);
?

2022-09-19 15:54 UTC, voropa requested changes

2022-09-19 15:54 UTC, voropa commented on src/test/java/Pages/ItemDetailPage.java
> +    private final static By clickContinueShoppingButton = By.xpath("//span[@title='Продолжить покупки']");
Все еще актуальный коментарий

2022-09-19 15:54 UTC, voropa commented on src/test/java/Pages/MyAccountPage.java
> +        Assert.assertFalse(alertText.isEmpty());
В page-классах не должно быть проверок, проверки должны быть в тестовых методах

2022-09-19 15:54 UTC, voropa commented on src/test/java/Tests/AuthenticationTests.java
> +        homePage.clickToSignOutButton();
Поччему у вас тест на signIn начинется с signOut() действия? Если это в результате работы прошлого теста дело, то нужно придумать какие-то before/afterMethod действия, чтобы тесты всегда начинались с одного и того же состояния

2022-09-19 15:54 UTC, voropa commented on src/test/java/Tests/AuthenticationTests.java
> +        homePage.clickToSignOutButton();
Тут то же самое

2022-09-19 15:54 UTC, voropa commented on src/test/java/Tests/BaseTest.java
> +    final static String EMAIL="asdfrewq@mail.ru";
Испольщуйте .properties file для хранения email / password

2022-09-19 16:54 UTC, MashaChornaya commented on src/test/java/Tests/AuthenticationTests.java
> +        homePage.clickToSignOutButton();
Смотрите, из-за того, что каждые сутки происходит обнуление аккаунтов,  приходится  делать тесты таким образом:  перед каждым тестом нужно  создавать  аккаунт.  И для того чтобы войти в аккаунт(SignInTest), его нужно прям перед этим создать, иначе будет ошибка типа "такого аккаунта не существует". Поэтому у меня в baseTest метод на создание аккаунта, а в authenticationTests уже на sign in

2022-09-19 16:58 UTC, MashaChornaya commented on src/test/java/Tests/BaseTest.java
> +    final static String EMAIL="asdfrewq@mail.ru";
Такс строку с EMAIL я вообще удалила, а следующая строка- переменная PASSWORD тут для negativeCreateAccountTest . Это просто данные (DataProvider)для создания аккаунта при котором будет выдаваться ошибка. В Prestashop похоже не получится сделать .properties file  так как аккаунты слетают через сутки и приходится их создавать перед каждым тестом с помощью faker((

2022-09-19 19:12 UTC, voropa commented on src/test/java/Tests/AuthenticationTests.java
> +        homePage.clickToSignOutButton();
Это понятно, но все равно не отменяет вопроса: почему у вас тест начинается с действия signOut(). Значит в before методе, где вы создаете аккаунт новый, делайте signOut сразу после создания, чтобы тесты не начинались с signOut(). Это странно выглядит, если не смотреть в before метод...

2022-09-19 19:15 UTC, voropa commented on src/test/java/Tests/BaseTest.java
> +    final static String EMAIL="asdfrewq@mail.ru";
Если это  тестовые данные, которые используются только в negativeCreateAccountTest, то и храните их в этом классе/методе, а не в BaseTest, потому что по названию этих констант и по  тому, что они находятся в BaseTest, складывается впечатление, что это какие-то глобальные e,ail/password, которые используются во всех тестах

2022-09-19 21:02 UTC, voropa requested changes
У вас вот тут ругается на несуществующую переменную, так что я не могу запустить тесты(
<img width="1491" alt="image" src="https://user-images.githubusercontent.com/14195681/191115860-f1434c73-d764-4114-8110-3b07c5e70776.png">

2022-09-20 17:21 UTC, MashaChornaya commented on src/test/java/Tests/AuthenticationTests.java
> +        homePage.clickToSignOutButton();
Я не могу так сделать. Метод signOut() у меня только в двух тестах : positiveSignInTest() и negativeCreateAccountTest, а в остальных тестах мне нужно быть залогининной, если я сделаю в beforeMethod SignOut,то тест ,например,на чекаут не пройдет так как в этом тесте нужно авторизоваться((

2022-09-20 17:23 UTC, MashaChornaya commented
странно, у меня с переменной всё ок, я сейчас еще раз скину этот класс
![image](https://user-images.githubusercontent.com/105201355/191324001-aad8f1c3-0fda-4fd9-b87a-f3e4b6901b46.png)

2022-09-20 17:31 UTC, voropa commented on src/test/java/Tests/AuthenticationTests.java
> +        homePage.clickToSignOutButton();
Значит вам нужно эти тесты разнести по разным классам, потому что у вас фактически 2 набора тестов в одном классе, для которых нужны разные pre-conditions

2022-09-20 18:12 UTC, voropa commented
Запустил все  ваши тесты, у меня 4 штуки упало( 
Еще и драйвер не закрывается после выполнения тестов
<img width="1664" alt="image" src="https://user-images.githubusercontent.com/14195681/191333070-66802f27-a4d2-4ef3-9946-fc04ed482685.png">

2022-09-20 19:31 UTC, MashaChornaya commented
![driver closed](https://user-images.githubusercontent.com/105201355/191343824-54eac60f-267c-463f-b8e3-54e2be72b503.png)

а почему не закрываться драйвер ?Есть же after class
У меня всё закрывается, после каждого теста...

2022-09-20 19:47 UTC, MashaChornaya commented
Только что запустила по раз 6 эти тесты : removeItemFromCartTest() ,addItemToCartTest(),actionsForPositiveCheckoutTest(),actionsForNegativeCheckoutTest()
У меня всё прошло. Оч странно. Я скину вам классы с этими тестами еще раз, может опять какая-то ошибка при загрузке  как с переменной

2022-09-21 08:25 UTC, voropa commented
> Только что запустила по раз 6 эти тесты : removeItemFromCartTest() ,addItemToCartTest(),actionsForPositiveCheckoutTest(),actionsForNegativeCheckoutTest() У меня всё прошло. Оч странно. Я скину вам классы с этими тестами еще раз, может опять какая-то ошибка при загрузке как с переменной

А вы как их запускаете? Через mvn clean test или прямо в IDEA?
Нжно чтобы через mvn clean test запускались все тесты и все работали. 
Драйвер не закрывается у вас, потому что в @afterClass методе у вас не стоит параметр alwaysRun = true, поэтому при щапуске через mvn он не отрабатывает(

2022-09-21 08:27 UTC, voropa commented
> > Только что запустила по раз 6 эти тесты : removeItemFromCartTest() ,addItemToCartTest(),actionsForPositiveCheckoutTest(),actionsForNegativeCheckoutTest() У меня всё прошло. Оч странно. Я скину вам классы с этими тестами еще раз, может опять какая-то ошибка при загрузке как с переменной
> 
> А вы как их запускаете? Через mvn clean test или прямо в IDEA? Нжно чтобы через mvn clean test запускались все тесты и все работали. Драйвер не закрывается у вас, потому что в @afterclass методе у вас не стоит параметр alwaysRun = true, поэтому при щапуске через mvn он не отрабатывает(

Добавьте в pom.xml все ваши сьюты и запустите mvn clean test - в таком случае запустятся все тесты и вот они должны стабильно все проходить

2022-09-22 08:55 UTC, voropa commented on src/test/java/Tests/CheckoutTests.java
> +    @Test(groups = {"Smoke","Negative"})
Странная категорищация этого теста. Обычно в смоук тесте не участвуют негативные тесты)

2022-09-22 09:20 UTC, voropa commented
У меня все-еще падает 4 теста ваших при запуске через mvn clean test
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/14195681/191709326-b5f87fe9-3be6-4891-8375-bae37fa55f15.png">

2022-09-25 06:58 UTC, voropa commented
Что-то результаты стали хуже, после ваших последних изменений: 8 упавших тестов
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/14195681/192132098-68f62fe2-8c5e-42bb-bedc-aff3453efde4.png">

2022-09-25 15:16 UTC, voropa requested changes

2022-09-25 15:16 UTC, voropa commented on src/test/java/Pages/ProductsPage.java
> +    private final static By casualDresses = By.xpath("//div[@id='categories_block_left']/descendant::li[1]");//("//div[@id='categories_block_left']/descendant::a[@href='http://prestashop.qatestlab.co
Почему по индексам? Там же ест ьтекст с названием категории товаров, например: //div[@id='categories_block_left']/descendant::a[contains(text(), 'Casual Dresses')]

И удалите закоментированый код

2022-09-25 16:33 UTC, voropa approved these changes

2022-09-25 17:55 UTC, merged